In [69]:
import pandas as pd
import json

### Match Results ###

In [77]:
with open('t20_json_files/t20_wc_match_results.json') as f:
    data=json.load(f)

In [78]:
df_match= pd.DataFrame(data[0]['matchSummary'])
df_match.tail()

,team1,team2,winner,margin,ground,matchDate,scorecard
40,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
41,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
42,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
43,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
44,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879

In [10]:
df_match.shape

(45, 7)

In [79]:
df_match.rename({'scorecard' : 'match_id'}, axis=1, inplace=True)

In [73]:
df_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [80]:
match_ids_dict = {}

for index,row in df_match.iterrows():
    key1 = row['team1'] + " Vs "+row['team2']
    key2 = row['team2'] + " Vs "+row['team1']
    
    match_ids_dict[key1]=row['match_id']
    match_ids_dict[key2]=row['match_id']

In [82]:
df_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [155]:
df_match.to_csv('t20_csv_files/dim_match_summary.csv')

### Batting Summary ###

In [83]:
with open('t20_json_files/t20_wc_batting_summary.json') as b:
    batting_data=json.load(b)

In [86]:
df_batting= pd.DataFrame(batting_data[0]['battingSummary'])
df_batting

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,c â€ Green b Shikongo,0,1,0,0,0.00
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,c la Cock b Scholtz,20,21,2,0,95.23
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),c â€ Green b Frylinck,29,23,2,1,126.08
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,c Loftie-Eaton b Scholtz,4,8,0,0,50.00
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,c Baard b Smit,5,8,0,0,62.50
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,run out (van Lingen/â€ Green),0,0,0,0,-
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,c Erasmus b Wiese,8,15,0,0,53.33
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,,11,11,0,1,100.00

In [87]:
df_batting= pd.DataFrame(batting_data[1]['battingSummary'])
df_batting

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,c â€ Edwards b van der Merwe,12,20,1,0,60.00
1,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,c Pringle b Klaassen,41,47,1,2,87.23
2,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,b Pringle,15,14,0,1,107.14
3,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravindâ€,c Klaassen b de Leede,18,21,0,0,85.71
4,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,run out (Ackermann/â€ Edwards),2,4,0,0,50.00
5,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,c van der Merwe b de Leede,4,4,1,0,100.00
6,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),b de Leede,1,2,0,0,50.00
7,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,c Cooper b Klaassen,5,7,0,0,71.42
8,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,,0,0,0,0,-
9,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,,0,1,0,0,0.00
10,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,b Basil Hameed,10,7,2,0,142.85
11,U.A.E. Vs Netherlands,Netherlands,2,Max O'Dowd,b Junaid Siddique,23,18,3,1,127.77
12,U.A.E. Vs Netherlands,Netherlands,3,Bas de Leede,c Rizwan b Meiyappan,14,18,1,0,77.77
13,U.A.E. Vs Netherlands,Netherlands,4,Colin Ackermann,c Junaid Siddique b Aayan Afzal Khan,17,19,1,0,89.47
14,U.A.E. Vs Netherlands,Netherlands,5,Tom Cooper,lbw b Junaid Siddique,8,16,0,0,50.00
15,U.A.E. Vs Netherlands,Netherlands,6,Scott Edwards(c)â€,,16,19,0,0,84.21
16,U.A.E. Vs Netherlands,Netherlands,7,Roelof van der Merwe,b Junaid Siddique,0,2,0,0,0.00
17,U.A.E. Vs Netherlands,Netherlands,8,Tim Pringle,b Zahoor Khan,15,16,0,0,93.75
18,U.A.E. Vs Netherlands,Netherlands,9,Logan van Beek,,4,4,0,0,100.00

In [88]:
all_records=[]

for rec in batting_data:
    all_records.extend(rec['battingSummary'])
                           
df_batting =pd.DataFrame(all_records)
df_batting.tail()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
694,Pakistan Vs England,England,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,2,0,111.11
695,Pakistan Vs England,England,4,Ben Stokes,,52,49,5,1,106.12
696,Pakistan Vs England,England,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,1,0,86.95
697,Pakistan Vs England,England,6,Moeen Ali,b Mohammad Wasim,19,13,3,0,146.15
698,Pakistan Vs England,England,7,Liam Livingstone,,1,1,0,0,100.00

In [89]:
df_batting['out/not_out'] = df_batting.dismissal.apply(lambda a : "out" if len(a)>0 else "not_out")
df_batting

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
...,...,...,...,...,...,...,...,...,...,...,...
694,Pakistan Vs England,England,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,2,0,111.11,out
695,Pakistan Vs England,England,4,Ben Stokes,,52,49,5,1,106.12,not_out
696,Pakistan Vs England,England,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,1,0,86.95,out
697,Pakistan Vs England,England,6,Moeen Ali,b Mohammad Wasim,19,13,3,0,146.15,out
698,Pakistan Vs England,England,7,Liam Livingstone,,1,1,0,0,100.00,not_out

In [90]:
df_batting.drop(columns=["dismissal"], inplace=True)
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,6,6,0,0,100.00,out

In [91]:
df_batting['batsmanName']=df_batting['batsmanName'].apply(lambda a: a.replace('â€',''))
df_batting['batsmanName']=df_batting['batsmanName'].apply(lambda a: a.replace('\xa0',''))

In [92]:
df_batting['match_id'] = df_batting['match'].map(match_ids_dict)

In [93]:
df_batting

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out,T20I # 1823
...,...,...,...,...,...,...,...,...,...,...,...
694,Pakistan Vs England,England,3,Phil Salt,10,9,2,0,111.11,out,T20I # 1879
695,Pakistan Vs England,England,4,Ben Stokes,52,49,5,1,106.12,not_out,T20I # 1879
696,Pakistan Vs England,England,5,Harry Brook,20,23,1,0,86.95,out,T20I # 1879
697,Pakistan Vs England,England,6,Moeen Ali,19,13,3,0,146.15,out,T20I # 1879
698,Pakistan Vs England,England,7,Liam Livingstone,1,1,0,0,100.00,not_out,T20I # 1879

In [94]:
df_batting.shape

(699, 11)

In [125]:
df_batting.to_csv('t20_csv_files/fact_batting_summary.csv', index=False)

### Bowlling Summary ###

In [115]:
with open('t20_json_files/t20_wc_bowling_summary.json') as bow :
    bowling_data=json.load(bow)

In [117]:
df_bowling=pd.DataFrame(bowling_data[0]['bowlingSummary'])
df_bowling

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0
5,Namibia Vs Sri Lanka,Namibia,Gerhard Erasmus,1,0,8,0,8.00,1,1,0,0,0
6,Namibia Vs Sri Lanka,Namibia,David Wiese,4,0,16,2,4.00,13,1,0,0,0
7,Namibia Vs Sri Lanka,Namibia,Bernard Scholtz,4,0,18,2,4.50,10,1,0,0,0
8,Namibia Vs Sri Lanka,Namibia,Ben Shikongo,3,1,22,2,7.33,6,3,0,0,0
9,Namibia Vs Sri Lanka,Namibia,JJ Smit,3,0,16,1,5.33,7,0,0,1,0
10,Namibia Vs Sri Lanka,Namibia,Jan Frylinck,4,0,26,2,6.50,10,0,2,1,0

In [123]:
all_records=[]

for rec in bowling_data:
    all_records.extend(rec['bowlingSummary']) 
 
df_bowling = pd.DataFrame(all_records)
df_bowling.head(50)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0
5,Namibia Vs Sri Lanka,Namibia,Gerhard Erasmus,1,0,8,0,8.00,1,1,0,0,0
6,Namibia Vs Sri Lanka,Namibia,David Wiese,4,0,16,2,4.00,13,1,0,0,0
7,Namibia Vs Sri Lanka,Namibia,Bernard Scholtz,4,0,18,2,4.50,10,1,0,0,0
8,Namibia Vs Sri Lanka,Namibia,Ben Shikongo,3,1,22,2,7.33,6,3,0,0,0
9,Namibia Vs Sri Lanka,Namibia,JJ Smit,3,0,16,1,5.33,7,0,0,1,0
10,Namibia Vs Sri Lanka,Namibia,Jan Frylinck,4,0,26,2,6.50,10,0,2,1,0
11,U.A.E. Vs Netherlands,Netherlands,Fred Klaassen,4,0,13,2,3.25,18,0,0,3,0
12,U.A.E. Vs Netherlands,Netherlands,Tim Pringle,4,0,13,1,3.25,11,0,0,0,0
13,U.A.E. Vs Netherlands,Netherlands,Logan van Beek,2,0,19,0,9.50,5,0,2,1,0
14,U.A.E. Vs Netherlands,Netherlands,Bas de Leede,3,0,19,3,6.33,9,2,0,2,0
15,U.A.E. Vs Netherlands,Netherlands,Paul van Meekeren,4,0,21,0,5.25,11,1,0,0,0
16,U.A.E. Vs Netherlands,Netherlands,Roelof van der Merwe,3,0,19,1,6.33,7,0,1,0,0
17,U.A.E. Vs Netherlands,U.A.E.,Junaid Siddique,4,0,24,3,6.00,10,2,0,1,0
18,U.A.E. Vs Netherlands,U.A.E.,Basil Hameed,1,0,7,1,7.00,4,0,1,0,0
19,U.A.E. Vs Netherlands,U.A.E.,Aayan Afzal Khan,3,0,15,1,5.00,8,1,0,0,0
20,U.A.E. Vs Netherlands,U.A.E.,Karthik Meiyappan,4,0,22,1,5.50,11,2,0,0,0
21,U.A.E. Vs Netherlands,U.A.E.,Zahoor Khan,4,0,11,1,2.75,14,0,0,0,0
22,U.A.E. Vs Netherlands,U.A.E.,Zawar Farid,2.5,0,24,0,8.47,2,2,0,0,0
23,U.A.E. Vs Netherlands,U.A.E.,Kashif Daud,1,0,5,0,5.00,1,0,0,0,0
24,Scotland Vs West Indies,West Indies,Kyle Mayers,2,0,24,0,12.00,5,5,0,2,0
25,Scotland Vs West Indies,West Indies,Akeal Hosein,4,0,31,0,7.75,8,2,1,0,0
26,Scotland Vs West Indies,West Indies,Alzarri Joseph,4,0,28,2,7.00,9,3,0,2,0
27,Scotland Vs West Indies,West Indies,Obed McCoy,3,0,25,0,8.33,6,4,0,0,0
28,Scotland Vs West Indies,West Indies,Jason Holder,3,0,14,2,4.66,8,1,0,0,0
29,Scotland Vs West Indies,West Indies,Odean Smith,4,0,31,1,7.75,6,3,0,1,0
30,Scotland Vs West Indies,Scotland,Mark Watt,4,0,12,3,3.00,16,1,0,1,0
31,Scotland Vs West Indies,Scotland,Brad Wheal,4,0,32,2,8.00,10,4,1,0,0
32,Scotland Vs West Indies,Scotland,Josh Davey,3,0,34,1,11.33,8,4,2,1,0
33,Scotland Vs West Indies,Scotland,Safyaan Sharif,3.3,0,23,1,6.57,7,2,0,2,0
34,Scotland Vs West Indies,Scotland,Michael Leask,4,0,15,2,3.75,11,0,0,1,0
35,Zimbabwe Vs Ireland,Ireland,Josh Little,4,0,24,3,6.00,11,3,0,0,0
36,Zimbabwe Vs Ireland,Ireland,Mark Adair,4,0,39,2,9.75,6,3,1,2,0
37,Zimbabwe Vs Ireland,Ireland,Barry McCarthy,4,0,24,0,6.00,11,2,0,2,0
38,Zimbabwe Vs Ireland,Ireland,Curtis Campher,3,0,29,0,9.66,6,2,2,0,0
39,Zimbabwe Vs Ireland,Ireland,Simi Singh,3,0,31,2,10.33,5,2,2,1,0
40,Zimbabwe Vs Ireland,Ireland,Gareth Delany,2,0,21,0,10.50,4,2,1,1,0
41,Zimbabwe Vs Ireland,Zimbabwe,Richard Ngarava,4,0,22,2,5.50,13,3,0,0,0
42,Zimbabwe Vs Ireland,Zimbabwe,Tendai Chatara,4,0,22,2,5.50,13,1,1,2,0
43,Zimbabwe Vs Ireland,Zimbabwe,Blessing Muzarabani,4,0,23,3,5.75,14,0,2,0,1
44,Zimbabwe Vs Ireland,Zimbabwe,Luke Jongwe,2,0,24,0,12.00,1,4,0,0,0
45,Zimbabwe Vs Ireland,Zimbabwe,Sean Williams,3,0,20,1,6.66,3,0,0,0,0
46,Zimbabwe Vs Ireland,Zimbabwe,Sikandar Raza,3,0,22,1,7.33,8,1,1,1,0
47,Namibia Vs Netherlands,Netherlands,Fred Klaassen,3,0,15,0,5.00,11,1,0,0,0
48,Namibia Vs Netherlands,Netherlands,Tim Pringle,3,0,15,1,5.00,8,0,0,0,0
49,Namibia Vs Netherlands,Netherlands,Bas de Leede,3,0,18,2,6.00,6,1,0,0,0

In [124]:
df_bowling['match_id'] = df_bowling['match'].map(match_ids_dict)
df_bowling

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Pakistan Vs England,Pakistan,Naseem Shah,4,0,30,0,7.50,15,3,1,1,0,T20I # 1879
496,Pakistan Vs England,Pakistan,Haris Rauf,4,0,23,2,5.75,13,3,0,1,0,T20I # 1879
497,Pakistan Vs England,Pakistan,Shadab Khan,4,0,20,1,5.00,10,1,0,0,0,T20I # 1879
498,Pakistan Vs England,Pakistan,Mohammad Wasim,4,0,38,1,9.50,5,5,0,2,0,T20I # 1879
499,Pakistan Vs England,Pakistan,Iftikhar Ahmed,0.5,0,13,0,15.60,0,1,1,0,0,T20I # 1879

In [128]:
df_bowling.to_csv('t20_csv_files/fact_bowling_summary.csv', index=False)

### Player Info

In [133]:
with open('t20_json_files/t20_wc_player_info.json') as p:
    data=json.load(p)

In [136]:
df_player_info = pd.DataFrame(data)

In [139]:
df_player_info.tail(50)

,name,team,battingStyle,bowlingStyle,playingRole,description
169,Lungi Ngidi,South Africa,Right hand Bat,Right arm Fast medium,Bowler,"A tall, imposing paceman, Lungi Ngidi can reac..."
170,Keshav Maharaj,South Africa,Right hand Bat,Slow Left arm Orthodox,Bowler,"A left-arm spinner from Northwood Boys High, t..."
171,Anrich Nortje,South Africa,Right hand Bat,Right arm Fast,Bowler,Anrich Nortje is a genuine quick who has been ...
172,Timm van der Gugten,Netherlands,Right hand Bat,Right arm Fast medium,Bowler,"Timm van der Gugten, born in Sydney, made his ..."
173,Finn Allen,New Zealand,Right hand Bat,,Top order Batter,
174,Devon Conwayâ€,New Zealand,Left hand Bat,Right arm Medium,Wicketkeeper Batter,
175,Kane Williamson(c),New Zealand,Right hand Bat,Right arm Offbreak,Top order Batter,By the time Kane Williamson is finished with p...
176,Glenn Phillips,New Zealand,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Glenn Phillips is a top-order wicketkeeper-bat...
177,James Neesham,New Zealand,Left hand Bat,Right arm Medium fast,Batting Allrounder,"Allrounder, and Twitter star, Jimmy Neesham we..."
178,Tim David,Australia,Right hand Bat,Right arm Offbreak,Middle order Batter,Mumbai Indians' decision to sign Tim David for...
179,Matthew Wadeâ€,Australia,Left hand Bat,Right arm Medium,Wicketkeeper Batter,It has been a career of reinvention for Matthe...
180,Adam Zampa,Australia,Right hand Bat,Legbreak Googly,Bowler,"An energetic and competitive legspinner, Adam ..."
181,Trent Boult,New Zealand,Right hand Bat,Left arm Fast medium,Bowler,Rated as one half of the best new-ball pair in...
182,Tim Southee,New Zealand,Right hand Bat,Right arm Medium fast,Bowler,"Tim Southee, a right-arm swing bowler, burst u..."
183,Mitchell Santner,New Zealand,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,"A left-handed batsman and left-arm spinner, Mi..."
184,Lockie Ferguson,New Zealand,Right hand Bat,Right arm Fast,Bowler,"A right-arm quick with a good bouncer, it is L..."
185,Ish Sodhi,New Zealand,Right hand Bat,Legbreak,Bowler,There is little in Ish Sodhi's statistics to s...
186,Aryan Lakra,U.A.E.,Left hand Bat,Slow Left arm Orthodox,Bowler,
187,Stephan Myburgh,Netherlands,Left hand Bat,Right arm Offbreak,Opening Batter,
188,Brandon Glover,Netherlands,Right hand Bat,Right arm Fast,Bowler,"A Dutch-South African fast bowler, Brandon Glo..."
189,Shoriful Islam,Bangladesh,Left hand Bat,Left arm Medium fast,Bowler,"At 6ft three inches, Shoriful Islam became a l..."
190,Daryl Mitchell,New Zealand,Right hand Bat,Right arm Medium,Allrounder,Daryl Mitchell was called into New Zealand's T...
191,Kasun Rajitha,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,"Virtually unheard of before 2015, the first in..."
192,Deepak Hooda,India,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."
193,Rilee Rossouw,South Africa,Left hand Bat,Right arm Offbreak,Top order Batter,A stylish top-order player with an elegant and...
194,Aiden Markram,South Africa,Right hand Bat,Right arm Offbreak,Opening Batter,The first South Africa captain to win a World ...
195,David Miller,South Africa,Left hand Bat,Right arm Offbreak,Middle order Batter,A hard-hitting left-hander with a penchant for...
196,Tristan Stubbs,South Africa,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,
197,Nasum Ahmed,Bangladesh,Left hand Bat,Slow Left arm Orthodox,Bowler,
198,Mohammad Haris,Pakistan,Right hand Bat,Right arm Offbreak,Middle order Batter,
199,Mohammad Wasim,Pakistan,Right hand Bat,Right arm Fast medium,Allrounder,
200,Ebadot Hossain,Bangladesh,Right hand Bat,Right arm Fast medium,Bowler,Ebadat Hossain Chowdhury's journey from being ...
201,Heinrich Klaasen,South Africa,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A clean-hitting, wicketkeeper batsman, Heinric..."
202,Brad Evans,Zimbabwe,Right hand Bat,Right arm Fast,Allrounder,
203,Fakhar Zaman,Pakistan,Left hand Bat,Slow Left arm Orthodox,Opening Batter,"Born in Mardan, where the standard of batsmans..."
204,Cameron Green,Australia,Right hand Bat,Right arm Fast medium,Batting Allrounder,Contracted to Western Australia as a schoolboy...
205,Steven Smith,Australia,Right hand Bat,Legbreak Googly,Middle order Batter,"In a career of twists and turns, Steven Smith ..."
206,Matthew Wade(c)â€,Australia,Left hand Bat,Right arm Medium,Wicketkeeper Batter,It has been a career of reinvention for Matthe...
207,Kane Richardson,Australia,Right hand Bat,Right arm Fast medium,Bowler,A pace bowler who has often been on the fringe...
208,Gulbadin Naib,Afghanistan,Right hand Bat,Right arm Medium fast,Batting Allrounder,Gulbadin Naib's first love in the sporting wor...
209,Darwish Rasooli,Afghanistan,Right hand Bat,Right arm Offbreak,Top order Batter,
210,Naveen-ul-Haq,Afghanistan,Right hand Bat,Right arm Medium fast,Bowler,
211,Rishabh Pantâ€,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."
212,Tony Munyonga,Zimbabwe,Right hand Bat,Right arm Offbreak,Allrounder,
213,Wellington Masakadza,Zimbabwe,Left hand Bat,Slow Left arm Orthodox,Bowler,
214,Tabraiz Shamsi,South Africa,Right hand Bat,Left arm Wrist spin,Bowler,A left-arm wristspin bowler with ample variati...
215,Phil Salt,England,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Phil Salt's fearless ball-striking at the top ...
216,Chris Jordan,England,Right hand Bat,Right arm Fast medium,Bowler,"Chris Jordan, a fast bowler with a level-heade..."
217,Regis Chakabva(c)â€,Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."
218,Mehidy Hasan Miraz,Bangladesh,Right hand Bat,Right arm Offbreak,Allrounder,Mehedi Hasan Miraz has emerged as one of the b...

In [151]:

df_player_info['name'] = df_player_info['name'].apply(lambda x: x.replace("â€",""))

df_player_info['name'] = df_player_info['name'].apply(lambda x: x.replace("\xa0",""))
df_player_info['name'] = df_player_info['name'].apply(lambda x: x.replace("†",""))

In [152]:
df_player_info

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
...,...,...,...,...,...,...
214,Tabraiz Shamsi,South Africa,Right hand Bat,Left arm Wrist spin,Bowler,A left-arm wristspin bowler with ample variati...
215,Phil Salt,England,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Phil Salt's fearless ball-striking at the top ...
216,Chris Jordan,England,Right hand Bat,Right arm Fast medium,Bowler,"Chris Jordan, a fast bowler with a level-heade..."
217,Regis Chakabva(c),Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."
218,Mehidy Hasan Miraz,Bangladesh,Right hand Bat,Right arm Offbreak,Allrounder,Mehedi Hasan Miraz has emerged as one of the b...

In [154]:
df_player_info.to_csv('t20_csv_files/dim_players_no_images.csv')